services:
  - type: web
    name: hoanglong-api
    runtime: node
    rootDir: sever
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: ADMIN_TOKEN_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: static
    name: hoanglong-web
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
